# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"\x07\n\x05\x45mpty\"B\n\x0b\x43hatMessage\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\t\"2\n\x0b\x43hatHistory\x12#\n\x08messages\x18\x01 \x03(\x0b\x32\x11.chat.ChatMessage\".\n\x0b\x43hatRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1a\n\tChatReply\x12\r\n\x05reply\x18\x01 \x01(\t\"6\n\x0cVideoRequest\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"\x1d\n\nVideoReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xa3\x01\n\x0b\x43hatService\x12\x31\n\x0bSendMessage\x12\x11.chat.ChatRequest\x1a\x0f.chat.ChatReply\x12\x33\n\x0bUploadVideo\x12\x12.chat.VideoRequest\x1a\x10.chat.VideoReply\x12,\n\nGetHistory\x12\x0b.chat.Empty\x1a\x11.chat.ChatHistoryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_CHATMESSAGE']._serialized_start=29
  _globals['_CHATMESSAGE']._serialized_end=95
  _globals['_CHATHISTORY']._serialized_start=97
  _globals['_CHATHISTORY']._serialized_end=147
  _globals['_CHATREQUEST']._serialized_start=149
  _globals['_CHATREQUEST']._serialized_end=195
  _globals['_CHATREPLY']._serialized_start=197
  _globals['_CHATREPLY']._serialized_end=223
  _globals['_VIDEOREQUEST']._serialized_start=225
  _globals['_VIDEOREQUEST']._serialized_end=279
  _globals['_VIDEOREPLY']._serialized_start=281
  _globals['_VIDEOREPLY']._serialized_end=310
  _globals['_CHATSERVICE']._serialized_start=313
  _globals['_CHATSERVICE']._serialized_end=476
# @@protoc_insertion_point(module_scope)
